export var nameList = [
    'Time','Past','Future','Dev',
    'Fly','Flying','Soar','Soaring','Power','Falling',
    'Fall','Jump','Cliff','Mountain','Rend','Red','Blue',
    'Green','Yellow','Gold','Demon','Demonic','Panda','Cat',
    'Kitty','Kitten','Zero','Memory','Trooper','XX','Bandit',
    'Fear','Light','Glow','Tread','Deep','Deeper','Deepest',
    'Mine','Your','Worst','Enemy','Hostile','Force','Video',
    'Game','Donkey','Mule','Colt','Cult','Cultist','Magnum',
    'Gun','Assault','Recon','Trap','Trapper','Redeem','Code',
    'Script','Writer','Near','Close','Open','Cube','Circle',
    'Geo','Genome','Germ','Spaz','Shot','Echo','Beta','Alpha',
    'Gamma','Omega','Seal','Squid','Money','Cash','Lord','King',
    'Duke','Rest','Fire','Flame','Morrow','Break','Breaker','Numb',
    'Ice','Cold','Rotten','Sick','Sickly','Janitor','Camel','Rooster',
    'Sand','Desert','Dessert','Hurdle','Racer','Eraser','Erase','Big',
    'Small','Short','Tall','Sith','Bounty','Hunter','Cracked','Broken',
    'Sad','Happy','Joy','Joyful','Crimson','Destiny','Deceit','Lies',
    'Lie','Honest','Destined','Bloxxer','Hawk','Eagle','Hawker','Walker',
    'Zombie','Sarge','Capt','Captain','Punch','One','Two','Uno','Slice',
    'Slash','Melt','Melted','Melting','Fell','Wolf','Hound',
    'Legacy','Sharp','Dead','Mew','Chuckle','Bubba','Bubble','Sandwich','Smasher','Extreme','Multi','Universe','Ultimate','Death','Ready','Monkey','Elevator','Wrench','Grease','Head','Theme','Grand','Cool','Kid','Boy','Girl','Vortex','Paradox'
];


export function generateRandomName() {
  const indianUsernames = [
    "Rajesh123",
    "AmitKumar",
    "SunitaVerma",
    "AnjaliSharma",
    "VikramSingh",
    "PriyaPatel",
    "ManojReddy",
    "KavitaGupta",
    "SureshYadav",
    "NishaMehta",
    "RaviChand",
    "DeepakJoshi",
    "SnehaNair",
    "ArjunBose",
    "PoojaIyer",
    "RahulDesai",
    "SeemaChawla",
    "VikasThakur",
    "NehaGarg",
    "KiranMishra",
    "AkashJain",
    "SanjayTiwari",
    "RinaKaur",
    "MaheshKulkarni",
    "KomalPandey",
    "KartikNaik",
    "SmitaChopra",
    "AshokGhosh",
    "LavanyaPillai",
    "RajivMalik",
    "VidyaMenon",
    "AnandDas",
    "ParulRana",
    "HarshaSingh",
    "NitinPatel",
    "ShaliniSinha",
    "GaneshShinde",
    "MeeraDevi",
    "PankajSaxena",
    "RuchiDubey",
    "JatinPandit",
    "SoniaKapoor",
    "YogeshVerma",
    "BhavnaDas",
    "HarishSehgal",
    "AartiRao",
    "SiddharthSethi",
    "TanviJoshi",
    "PrakashYadav",
    "AnushkaBatra",
    "MukeshArora",
    "ChandniBedi",
    "NaveenChandra",
    "GeetaRawat",
    "PunitNanda",
    "AvinashKaul",
    "SapnaBajpai",
    "OmkarSharma",
    "ShreyaDasgupta",
    "NarayanBhat",
    "RekhaRaj",
    "VishalTrivedi",
    "KajalVerma",
    "SahilKohli",
    "AnkitaDas",
    "GauravMehra",
    "MonaShukla",
    "DevendraShah",
    "PreetiMathur",
    "RohitChadha",
    "MeghnaReddy",
    "RameshRana",
    "ShrutiKapadia",
    "AjayNaik",
    "TanyaMenon",
    "KrishnaMohan",
    "AshaShetty",
    "SumitKumar",
    "PriyankaJha",
    "SanjanaSen",
    "DineshVerma",
    "PallaviBasu",
    "ArunChakraborty",
    "JyotiMalhotra",
    "ChetanGoel",
    "NandiniIyer",
    "AmritaChoudhary",
    "KunalRao",
    "MadhuriPatil",
    "VijayBhatt",
    "RituKhurana",
    "AshwiniPai",
    "SameerJoshi",
    "BhaskarDas",
    "KarishmaShah",
    "PiyushRana",
    "TrishaBanerjee",
  ];

  // Select a random username
  const randomIndex = Math.floor(Math.random() * indianUsernames.length);
  return indianUsernames[randomIndex];
};

export function generateRandomMessage() {
  const chatMessages = [
    "Hello everyone!", "How's it going?", "What a great stream!", "Loving the content!", 
    "Any updates on that?", "Can you share the link?", "Amazing quality!", "This is so helpful!", 
    "Thanks for the tips!", "Haha, that's funny!", "Wow, didn’t know that!", "Learning so much here.", 
    "Great explanation!", "You're the best!", "Can you repeat that?", "What’s next on the agenda?", 
    "Such a chill vibe here.", "Is this recorded?", "Hello from India!", "Keep it up!", 
    "When’s the next live?", "Any suggestions for beginners?", "That was awesome!", 
    "Please slow down a bit.", "What a pro!", "Subscribed right now!", "What tools do you use?", 
    "Can I DM you?", "This is a game-changer!", "How long have you been doing this?", 
    "Big fan from Mumbai!", "I’m taking notes!", "Any book recommendations?", "You're so underrated!", 
    "What's your favorite tool?", "Can we get a quick recap?", "This chat is so active!", 
    "Loved that example.", "Great energy in this live!", "Shoutout to the host!", "This is GOLD!", 
    "I’m here every stream!", "When’s the next Q&A?", "What’s your setup?", "This is going viral!", 
    "So relatable!", "Where do I start?", "How can I support you?", "Mind-blowing stuff!", 
    "Great pacing so far.", "Is there a replay link?", "Any giveaways today?", "This is why I subscribed!", 
    "Love the interaction here.", "Do you have a blog?", "Where can I learn more?", 
    "Who else is enjoying this?", "Can you clarify that part?", "Hello from Bangalore!", 
    "Can we collab sometime?", "What’s your inspiration?", "Does this work globally?", 
    "Biggest fan here!", "This makes so much sense!", "Can we get some examples?", "Love your passion!", 
    "So excited for this!", "This is pure value!", "Where can I follow you?", "Epic content!", 
    "You explain things so well!", "Can you recommend tools?", "What’s the timeline for this?", 
    "Perfect timing for this stream!", "Your content is so consistent!", "How can I get started?", 
    "Any insider tips?", "You’re a natural at this!", "OMG, so true!", "This is top-tier!", 
    "How do you stay motivated?", "What’s your background?", "So cool!", "This is genius!", 
    "How do you manage everything?", "I’ve learned so much here.", "This is a whole vibe.", 
    "Do you offer courses?", "Such a supportive community!", "This is so well-organized!", 
    "How do you balance this?", "Do you have a podcast?", "Love the positivity here.", 
    "Can you recommend books?", "What’s your secret sauce?", "How do you edit so well?", 
    "What software do you use?", "This chat is popping!", "What inspired you to start?", 
    "Your voice is so calming!", "Can we get a playlist?", "Do you do 1-on-1 sessions?", 
    "This is life-changing!", "How do you come up with ideas?", "This is next level!", 
    "Such a creative stream!", "You’re my role model!", "What’s your advice for newbies?", 
    "How do you stay consistent?", "What’s the key takeaway?", "Thanks for sharing this!", 
    "How do you manage time?", "This is exactly what I needed!", "How long does this take?", 
    "Where do you see this going?", "This chat is fire!", "Do you livestream often?", 
    "What’s your upload schedule?", "So inspiring!", "Can you break that down further?", 
    "What’s the easiest way to start?", "So glad I tuned in!", "This is pure gold!", 
    "What challenges do you face?", "How do you handle setbacks?", "Your editing is so smooth!", 
    "What motivates you?", "So relatable, love it!", "What’s your dream project?", 
    "This stream is flawless!", "You’re so authentic!", "What’s the hardest part about this?", 
    "How do you plan your content?", "This is so practical!", "Love the visuals here.", 
    "Can we expect more of this?", "This deserves more views!", "How can we support you?", 
    "What’s the highlight of this?", "Your dedication is inspiring!", "What’s next for you?", 
    "This is so rewarding!", "Any apps you recommend?", "This is why I follow you!", 
    "Do you mentor people?", "How do you balance quality and speed?", "How do you track progress?", 
    "Your enthusiasm is contagious!", "This is a breath of fresh air!", "How do you deal with stress?", 
    "What’s your long-term goal?", "Do you collab with others?", "What’s your favorite part about this?", 
    "This is a work of art!", "What’s the best advice you’ve received?", "This is 10/10!", 
    "How do you learn so fast?", "What’s your favorite tool?", "This is pure inspiration!", 
    "Any upcoming surprises?", "Can you demo that?", "This is beautifully explained!", 
    "What’s your favorite book?", "Can you simplify that?", "This is top-notch!", 
    "What’s your workflow like?", "How do you avoid burnout?", "Can you recommend tools?", 
    "This is so professional!", "What’s your biggest challenge?", "This is beyond expectations!", 
    "What’s your proudest moment?", "This community is amazing!", "How do you keep things fresh?", 
    "What’s your advice for growth?", "This is a great resource!", "Can you share templates?", 
    "This deserves an award!", "What’s the biggest takeaway?", "How do you handle feedback?", 
    "This stream is flawless!", "You’re so genuine!", "What’s the biggest misconception?", 
    "How do you build confidence?", "This is all we needed!", "Your work ethic is inspiring!", 
    "What’s your editing workflow?", "How do you come up with content?", "Can we get behind-the-scenes?", 
    "What’s your advice for consistency?", "This is so encouraging!", "What’s the hardest skill to learn?", 
    "This is so impactful!", "What’s the secret to success?", "This is phenomenal!", "You’re a legend!", 
    "What’s your next project?", "Can we get a roadmap?", "What’s the most underrated tip?", 
    "This is a masterpiece!", "How do you deal with negativity?", "This is the gold standard!", 
    "What’s your biggest inspiration?", "Can you share your goals?", "This stream is legendary!", 
    "What’s the most common mistake?", "This is way beyond expectations!", "What’s your personal mantra?", 
    "This chat is so wholesome!", "What’s your ultimate goal?", "This is the perfect balance!", 
    "What’s the key to success?", "Can you share your journey?", "This is truly world-class!", 
    "How do you refine your skills?", "This is absolutely worth it!", "You’re so relatable!", 
    "What’s your biggest learning?", "This is pure brilliance!", "How do you ensure quality?", 
    "This is a fantastic resource!", "Can you share quick tips?", "This is the epitome of creativity!", 
    "What’s your strategy for growth?", "This is pure magic!", "What’s your favorite tool?", 
    "How do you handle tough situations?", "This is pure value!", "What’s the biggest takeaway?", 
    "How do you simplify complex things?", "This is a blessing!", "What’s the most rewarding part?", 
    "This is absolutely brilliant!", "What’s your go-to tool?", "How do you master your craft?", 
    "This is incredibly insightful!", "What’s the most surprising tip?", "How do you stay innovative?", 
    "This is top-class content!", "What’s your biggest achievement?", "This is all we needed!", 
    "What’s the most important lesson?", "This is an eye-opener!", "What’s your advice for new creators?", 
    "This is simply amazing!"
  ];

  // Select a random message
  const randomIndex = Math.floor(Math.random() * chatMessages.length);
  return chatMessages[randomIndex];
}